export const DATABASE_POOL = Symbol('DATABASE_POOL');
export const META_CONNECTION_REPOSITORY = Symbol('META_CONNECTION_REPOSITORY');
export const META_OAUTH_ATTEMPT_REPOSITORY = Symbol('META_OAUTH_ATTEMPT_REPOSITORY');
export const CAPABILITY_REPOSITORY = Symbol('CAPABILITY_REPOSITORY');
export const READINESS_REPOSITORY = Symbol('READINESS_REPOSITORY');
export const SMOKE_TEST_REPORT_REPOSITORY = Symbol('SMOKE_TEST_REPORT_REPOSITORY');
export const CAMPAIGN_CONTEXT_REPOSITORY = Symbol('CAMPAIGN_CONTEXT_REPOSITORY');
export const EXECUTION_PLAN_REPOSITORY = Symbol('EXECUTION_PLAN_REPOSITORY');
export const APPROVAL_REPOSITORY = Symbol('APPROVAL_REPOSITORY');
export const AUDIT_REPOSITORY = Symbol('AUDIT_REPOSITORY');
export const EXECUTION_SIMULATION_REPOSITORY = Symbol('EXECUTION_SIMULATION_REPOSITORY');
export const CREATIVE_PACKAGE_REPOSITORY = Symbol('CREATIVE_PACKAGE_REPOSITORY');
export const OPERATIONAL_READINESS_REPOSITORY = Symbol('OPERATIONAL_READINESS_REPOSITORY');
export const EXECUTION_MANIFEST_REPOSITORY = Symbol('EXECUTION_MANIFEST_REPOSITORY');
export const EXECUTION_AUTHORIZATION_REPOSITORY = Symbol('EXECUTION_AUTHORIZATION_REPOSITORY');
export const KILL_SWITCH_REPOSITORY = Symbol('KILL_SWITCH_REPOSITORY');
export const META_WRITE_VALIDATION_PROTOCOL_REPOSITORY = Symbol(
  'META_WRITE_VALIDATION_PROTOCOL_REPOSITORY',
);
export const OPERATOR_TENANT_MEMBERSHIP_REPOSITORY = Symbol(
  'OPERATOR_TENANT_MEMBERSHIP_REPOSITORY',
);
