export const DATABASE_POOL = Symbol('DATABASE_POOL');
export const META_CONNECTION_REPOSITORY = Symbol('META_CONNECTION_REPOSITORY');
export const META_OAUTH_ATTEMPT_REPOSITORY = Symbol('META_OAUTH_ATTEMPT_REPOSITORY');
export const CAPABILITY_REPOSITORY = Symbol('CAPABILITY_REPOSITORY');
export const READINESS_REPOSITORY = Symbol('READINESS_REPOSITORY');
export const SMOKE_TEST_REPORT_REPOSITORY = Symbol('SMOKE_TEST_REPORT_REPOSITORY');
