import { loadOperatorWorkQueue } from '../../../lib/operator-work-queue.mjs'
import { deriveOperatorBlockerConcentration } from '../../../lib/operator-blocker-concentration.mjs'

export default async function BlockerConcentrationPage() {
  const result = await loadOperatorWorkQueue()
  if (result.kind !== 'ready') return <main className="portfolio-state"><span className="eyebrow">Concentração de bloqueios</span><h1>Dados não confirmados.</h1><a href="/work-queue">Voltar à fila</a></main>
  const view = deriveOperatorBlockerConcentration(result.queue)
  return <><header className="topbar"><a className="brand" href="/"><span className="brand-mark">C</span><span><strong>Contexto Ads</strong><small>Concentração de bloqueios</small></span></a><div className="environment"><span />Somente leitura</div></header><main className="work-shell"><section className="work-hero"><div><span className="eyebrow">Padrões comprovados</span><h1>Quais bloqueios se repetem entre clientes.</h1><p>A visão agrupa somente blocker codes atuais. Repetição não é tratada como causa, tendência ou score de risco.</p></div><a href="/work-queue">Voltar à fila</a></section><section className="work-metrics"><article><span>Blocker codes</span><strong>{view.blockers.length}</strong></article><article><span>Repetidos entre clientes</span><strong>{view.repeatedAcrossTenantsCount}</strong></article></section><section className="work-list">{view.blockers.map((blocker)=><article className={`work-item work-${blocker.highestPriority}`} key={blocker.blockerCode}><div className="work-item-head"><div><span>{blocker.highestPriority}</span><h3>{blocker.blockerCode}</h3><small>{blocker.tenantCount} cliente(s) · {blocker.itemCount} item(ns)</small></div></div><p>Responsáveis presentes: {blocker.owners.join(', ')}. Prioridades presentes: {blocker.priorities.join(', ')}.</p></article>)}</section><div className="portfolio-boundary">Agrupamento descritivo apenas. Nenhuma causa, risco futuro, prazo ou ação externa foi inferida.</div></main></>
}
