import { loadOperatorWorkQueue } from '../../../lib/operator-work-queue.mjs'
import { deriveOperatorCommandCenter } from '../../../lib/operator-command-center.mjs'

export default async function OperatorCommandCenterPage(){
  const result=await loadOperatorWorkQueue()
  if(result.kind!=='ready') return <main className="portfolio-state"><span className="eyebrow">Central de comando</span><h1>Dados não confirmados.</h1><a href="/work-queue">Voltar à fila</a></main>
  const view=deriveOperatorCommandCenter(result.queue)
  return <><header className="topbar"><a className="brand" href="/"><span className="brand-mark">C</span><span><strong>Contexto Ads</strong><small>Central de comando</small></span></a><div className="environment"><span />Somente leitura</div></header><main className="work-shell"><section className="work-hero"><div><span className="eyebrow">Visão consolidada</span><h1>Um índice para a operação diária.</h1><p>Todos os números abaixo vêm da fila e das comparações já validadas. Nenhuma métrica sintética ou novo estado operacional é criado.</p></div><a href="/work-queue">Abrir fila</a></section><section className="work-metrics"><article><span>Pendências</span><strong>{view.pendingCount}</strong></article><article><span>Críticas</span><strong>{view.criticalCount}</strong></article><article><span>Operador</span><strong>{view.operatorCount}</strong></article><article><span>Ambiente Meta</span><strong>{view.metaEnvironmentCount}</strong></article><article><span>Entrou/piorou</span><strong>{view.enteredOrWorsenedCount}</strong></article><article><span>Resolvidas</span><strong>{view.resolvedCount}</strong></article><article><span>Sem baseline</span><strong>{view.baselineMissingCount}</strong></article></section><section className="work-list">{view.navigation.map(([href,label])=><article className="work-item" key={href}><div className="work-item-head"><div><span>Visão derivada</span><h3>{label}</h3></div><a href={href}>Abrir →</a></div></article>)}</section><div className="portfolio-boundary">Índice derivado somente de dados já validados. Nenhum novo estado, score sintético, prazo ou escrita externa foi criado.</div></main></>
}
